spring:
  profiles:
    default: local
    group:
      "local": "dev"
      "prod": "prod"

#default resilience4j config
resilience4j.timelimiter:
  instances:
    default:
      timeoutDuration: 10000ms
      cancelRunningFuture: true
resilience4j.circuitbreaker:
  instances:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 10
      slidingWindowType: TIME_BASED