server:
  port: 8081

iam:
  clientId: 59710622-6c26-4e38-9633-1680e66abfe5
  clientSecret: ANPTPaTeHXbeJcXTdmcFR1x8Fbi2OTbvGbwb7BVMBB14iOdcSKngmwhzaBYclKbn6Gk1Hv8wyQlVwygFv2FPFrY
  introspect:
    host: http://localhost:8080
    url: /introspect

template:
  withSsl: false
  connectionTimeout: 3000
  readTimeout: 3000