server:
  port: 443
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password

iam:
  scim:
    host: http://127.0.0.1:8080
    path: /scim/Me

#resilience4j:
#  bulkhead:
#    instances:
#      iam-profile:
#        maxWaitDuration: 1ms
#        maxConcurrentCall: 2
#  thread-pool-bulkhead:
#    instances:
#      iam-profile:
#        maxThreadPoolSize: 1
#        coreThreadPoolSize: 1
#        queueCapacity: 1

rest-template:
  verifyHostName: false
  withSsl: true
  connectionRequestTimeout: 3000
  connectTimeout: 3000
  readTimeout: 3000

resilience4j.timelimiter:
  instances:
    iam-profile:
      timeoutDuration: 1000ms
      cancelRunningFuture: true
resilience4j.circuitbreaker:
  instances:
    iam-profile:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: TIME_BASED

logging:
  level:
    root: INFO
    com.tw.gms: DEBUG