spring:
  profiles:
    default: default, resilient

server:
  port: ${GMS_APPLICATION_PORT:443}
  ssl:
    key-store: ${GMS_KEYSTORE_PATH:classpath:springboot.p12}
    key-store-password: ${GMS_KEYSTORE_PASSWORD:password}
    key-store-type: ${GMS_KEYSTORE_TYPE:pkcs12}
    key-alias: ${GMS_KEY_ALIAS:springboot}
    key-password: ${GMS_KEY_PASSWORD:password}

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS}|%level|%logger.%M|%X{uuid}|%X{uri}|%X{method}|%msg%n"
  level:
    root: INFO
    com.tw.gms: ${GMS_APPLICATION_LOGGING_LEVEL:INFO}

resilience4j.timelimiter:
  instances:
    default:
      timeoutDuration: ${RESILIENT_TIMEOUT_DURATION_DEFAULT:10000ms}
      cancelRunningFuture: true
resilience4j.circuitbreaker:
  instances:
    default:
      registerHealthIndicator: true
      slidingWindowSize: ${RESILIENT_SLIDING_WINDOW_SIZE_DEFAULT:20}
      permittedNumberOfCallsInHalfOpenState: ${RESILIENT_PERMITTED_NUMBER_OF_OPEN_CALLS_DEFAULT:10}
      slidingWindowType: TIME_BASED

iam:
  scim:
    host: ${IAM_HOST:http://localhost:8080}
    path: /scim/Me

rest-template:
  verifyHostName: ${REST_TEMPLATE_VERIFY_HOST_NAME:true}
  withSsl: ${REST_TEMPLATE_WITH_SSL:true}
  validateCertificateChain: ${REST_TEMPLATE_VALIDATE_CERTIFICATE_CHAIN:false}
  connectionRequestTimeout: ${REST_TEMPLATE_CONNECTION_REQUEST_TIMEOUT:3000}
  connectTimeout: ${REST_TEMPLATE_CONNECT_TIMEOUT:3000}
  readTimeout: ${REST_TEMPLATE_READ_TIMEOUT:3000}