
# capabilities config
scheme: http
proxyName: localhost
proxyPort: 8080


# iam apis
iam:
  apis:
    currentUser: /scim/Me


password-grant-flow:
  isEnabled: true


scim-read-client:
  batchSize: 50
  maxBatchCount: 5