
# capabilities config
scheme: http
proxyName: localhost
proxyPort: 8080

# iam api configs
iam:
  userinfo:
    path: /userinfo
    timeout: 5
  clientCredentialToken: 
    path: /token
    timeout: 5
    clientId: ${CLIENT_CREDETIAL_ID}
    clientSecret: ${CLIENT_CREDETIAL_SECRET}
  fetchUserById:
    path: /scim/Users/{userId}
    timeout: 10