
server:
  port: ${SERVER_PORT:8080}
  capabilities:
    path: ${CAPABILITIES_PATH:/resources/capabilities.xml}
    config:
      scheme: ${TOMCAT_CONNECTOR_SCHEME:http}
      proxyName: ${TOMCAT_CONNECTOR_PROXY_NAME:localhost}
      proxyPort: ${TOMCAT_CONNECTOR_PROXY_PORT:8080}


# iam api configs
iam:
  userinfo:
    path: /userinfo
    timeout: 5
  clientCredentialToken:
    path: /token
    timeout: 5
    clientId: ${CLIENT_CREDETIAL_ID:client}
    clientSecret: ${CLIENT_CREDETIAL_SECRET:client_secret}
  fetchUserById:
    path: /scim/Users/{userId}
    timeout: 10