apiVersion: v1
kind: Service
metadata:
  name: db-view
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql 

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: iam
        - name: MYSQL_USER
          value: iam
        - name: MYSQL_ROOT_PASSWORD
          value: pwd
        - name: MYSQL_PASSWORD
          value: pwd
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: keystore-configmap
data:
  keystore.jwks: |
    {
      "keys": [
        {
          "p": "-qdvzeHU7w_ToV2RlS2QlVggXNL2YfpRWQxvrO8pHZC_dVgYFwKz5nadOMzR1BK0tPuCTWuuI66sFgaA9VENGypdIYoCF2O1FBLFK6GjOO-uc0LZEbIDa6Xn0G7UYOWcLaiYriHTtC_Pzp11L7VGjrUlX4HRgU_B3X1oeGn0mbM",
          "kty": "RSA",
          "q": "5S2b9tYHi9zBcNGZ8X6GM4TAL4UU9mABH0rKIyzbudkG7Wxxbj6I18skuHzfOOPI4c8sTQSv6IVAr2n1bn3_E5RSyPpbtDSCTYGzhijXl9wZ0ba2NidFrVjnL-KPx_gcHKnUHebKvsIEdjxeuqaaZ1kqEJX326b450Frghd78p8",
          "d": "oDb1qfQTaP73jEZHgkOG5C9dY5EJZW57fX_BYUJ-yYTuTHPWZBVDKw9I_Ir1tSYyuTF-Bfb4iPim46gnEBM3AdvMian2iajvrN_rJFUJHo65vtY9xCXCD0d_Jct5JMyOafP5LF3cP38yDcyZRS_JeyKGB6U1KhbL-gG4hrQGS8qO3rdY_JQiLDLVdRRptHsPphS44JHXdP2qeVNJ41-CTfPWKiMIUOC0fj-As-dbTzRXuLXs04NayAdM-yhvRiwKujEfL8YbKW9CDJIgJfm2vzWHXFus5Y11S2Zr65cWxxVvRfnAFbFO1AkIkJc2jHZ4xLxfDU2kTi20sOMq1UFrvQ",
          "e": "AQAB",
          "kid": "rsa1",
          "qi": "bN1wnq_0VkJlECMGPmeRFdZCX2LgAMrgwbJpysRw5J04vO9YsVmAcB_4xqoDjDUg7koioAp3IOhMGjOJWpYzCqWzsaA_84kX4WKGsr2xz6oaFSgt1FvtBY4GqEeZj8RG0LMtEtKSyjHGieA0hd4TUcqSdNZ4osT98Bfd7z3peYc",
          "dp": "YfyaxI2IRHyXavm9M-hAIWH2JNOD5gGJU5p8_cnw9NHlRuZNZJF16p5sEAxh6tn1MtsvsTxrMx_RvjqEp2IsEXaaOcZN0v7zhwlfcxMZT-TC-eQkH7rLg4Wz_dOVytt4FpFWPpySuloGjusXKLNhBeDi31dMo5SeYQvpj0k8iek",
          "dq": "9_lhyLPNdohmxqwE5kkA7L23NbPJ-svmavWBwo3HMlCiLkQoeCEx8EzebsCux9-wfKSuSqfHrtCALU15QxUR6x2SdeRvVY17cGHm3kNTA_4j8cbBYdccjXSksitzZ-wOfvVDjxcqST2llkm8NjoO18Siv0-F4SXKLG-c5CaE9w",
          "n": "4GRvJuFantVV3JdjwQOAkfREnwUFp2znRBTOIJhPamyH4gf4YlI5PQT79415NV4_HrWYzgooH5AK6-7WE-TLLGEAVK5vdk4vv79bG7ukvjvBPxAjEhQn6-Amln88iXtvicEGbh--3CKbQj1jryVU5aWM6jzweaabFSeCILVEd6ZT7ofXaAqan9eLzU5IEtTPy5MfrrOvWw5Q7D2yzMqc5LksmaQSw8XtmhA8gnENnIqjAMmPtRltf93wjtmiamgVENOVPdN-93Nd5w-pnMwEyoO6Q9JqXxV6lD6qBRxI7_5t4_vmVxcbbxcZbSAMoHqA2pbSMJ4Jcw-27Hct9jesLQ"
        }
      ]
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - name: iam
        image: indigoiam/iam-login-service:v1.8.4
        volumeMounts:
        - name: keystore-volume
          mountPath: /keystore
          readOnly: true
        env:
        - name: IAM_JAVA_OPTS
          value: "-Dspring.profiles.active=prod,registration,oidc,saml -Dspring.datasource.url=jdbc:mysql://db-service.default.svc.cluster.local:3306/iam?allowPublicKeyRetrieval=true&useSSL=false -Djava.security.egd=file:/dev/./urandom"
        - name: IAM_HOST
          value: iam-view.default.svc.cluster.local:8080
        - name: IAM_BASE_URL
          value: http://iam-view.default.svc.cluster.local:8080
        - name: IAM_ISSUER
          value: http://iam-view.default.svc.cluster.local:8080
        - name: IAM_FORWARD_HEADERS_STRATEGY
          value: native
        - name: IAM_DB_ALLOW_PUBLIC_KEY
          value: "true"
        - name: IAM_KEY_STORE_LOCATION
          value: file:/keystore/keystore.jwks
        - name: IAM_DB_USERNAME
          value: root
        - name: IAM_DB_PASSWORD
          value: pwd
        - name: IAM_X509_CAN_LOGIN
          value: "true"
        - name: IAM_LOG_LEVEL
          value: DEBUG
        resources:
          requests:
            memory: "1564Mi"
            cpu: "3000m"
          limits:
            memory: "1564Mi"
            cpu: "3000m"
      volumes:
      - name: keystore-volume
        configMap:
            name: keystore-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: iam-service
spec:
  selector:
    app: iam
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: iam-view
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: iam 